# MPark.Variant
#
# Copyright Michael Park, 2015-2017
#
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.md or copy at http://boost.org/LICENSE_1_0.txt)

language: cpp
sudo: false

branches:
  only:
    - master

git:
  depth: 1

env:
  global:
    - secure: jL8hAVoa2B512uGeoh5DL2YXrAznfKPz3GbcaUPzR6mR2Izj2yHFihLLeHrEY8vUdadS8zbn2CwtWnmJjNz5kIT/RxESxJJtgVNruwo0u4piIfxVI/tTRObMXKaGrfquDAHS/hjAhQlPSNNr+89oFSBvSfNpAVECd/ERhhnjIugD+MFFzaxi26qvM6li9toxPNJIxBq9jHRuZzlpWez6d6RcTsaqr30BaCEuJhVcg7J4SiSL8xeW2sokAG65pZ/aig23cCSJkhazbMd7Cy/OFNjQrhc2PQ+E0c2xEwdwCNA8qTnsMrUeo9NXc+lozOf23LWD1EvZtcNNG5arPhSuGGYs90T1GdL2jqyS1E+1Xf0cOWqB4VMho7H+vV55SgZb+TYDrmB63YvgxcUKgsDRvPI9bBv3S3uxgktbE6gwnrfQirKowbscC07X3R1RJiI6hSkVNdrLnQF28BHMRlCpyhDejIWm4qHgOrWCN+I6hZtk+nsRuJF8sCSFPUWuzlG+/kSwaBwm/eEy+ZI66ufJamHUqC8bxa+6kINxtJTMN79ZnbIPwOvey9cfVfzwxefaStwpQbCJuZlMbuo4738HxUQpscxgv6LA5ZEMz8hlKO82cWDZSEDxSrUowueu1Az0u5tfzBUXaU5pZCnGdK6aMGHcTznaeUFebq8uhLR3uc0=

jobs:
  include:
    # ubuntu 14.04, gcc-4.8
    - env: VER=4.8 CXX_VERSIONS="11;1y" TESTS="mpark"
      compiler: gcc
      os: linux
      addons: { apt: { packages: ["g++-4.8"], sources: ["ubuntu-toolchain-r-test"] } }

    # ubuntu 14.04, gcc-4.9
    - env: VER=4.9 CXX_VERSIONS="11;14" TESTS="mpark"
      compiler: gcc
      os: linux
      addons: { apt: { packages: ["g++-4.9"], sources: ["ubuntu-toolchain-r-test"] } }

    # ubuntu 14.04, gcc-5
    - env: VER=5 CXX_VERSIONS="11;14;1z" TESTS="mpark"
      compiler: gcc
      os: linux
      addons: { apt: { packages: ["g++-5"], sources: ["ubuntu-toolchain-r-test"] } }

    # ubuntu 14.04, gcc-6
    - env: VER=6 CXX_VERSIONS="11;14;1z" TESTS="mpark"
      compiler: gcc
      os: linux
      addons: { apt: { packages: ["g++-6"], sources: ["ubuntu-toolchain-r-test"] } }

    # ubuntu 14.04, gcc-7
    - env: VER=7 CXX_VERSIONS="11;14;17" TESTS="mpark;libc++"
      compiler: gcc
      os: linux
      addons: { apt: { packages: ["g++-7"], sources: ["ubuntu-toolchain-r-test"] } }

    # ubuntu 14.04, clang-3.6
    - env: VER=3.6 CXX_VERSIONS="11;14" TESTS="mpark"
      compiler: clang
      os: linux
      addons: { apt: { packages: ["clang-3.6", "libstdc++-5-dev"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-precise-3.6"] } }

    # ubuntu 14.04, clang-3.7
    - env: VER=3.7 CXX_VERSIONS="11;14" TESTS="mpark"
      compiler: clang
      os: linux
      addons: { apt: { packages: ["clang-3.7", "libstdc++-5-dev"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-precise-3.7"] } }

    # ubuntu 14.04, clang-3.8
    - env: VER=3.8 CXX_VERSIONS="11;14" TESTS="mpark"
      compiler: clang
      os: linux
      addons: { apt: { packages: ["clang-3.8", "libstdc++-5-dev"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-precise-3.8"] } }

    # ubuntu 14.04, clang-3.9
    - env: VER=3.9 CXX_VERSIONS="11;14;1z" TESTS="mpark"
      compiler: clang
      os: linux
      addons: { apt: { packages: ["clang-3.9", "libstdc++-6-dev"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-trusty-3.9"] } }

    # ubuntu 14.04, clang-4.0
    - env: VER=4.0 CXX_VERSIONS="11;14;1z" TESTS="mpark"
      compiler: clang
      os: linux
      addons: { apt: { packages: ["clang-4.0", "libstdc++-6-dev"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-trusty-4.0"] } }

    # ubuntu 14.04, clang-5.0
    - env: VER=5.0 CXX_VERSIONS="11;14;17" TESTS="mpark;libc++"
      compiler: clang
      os: linux
      addons: { apt: { packages: ["clang-5.0", "libstdc++-7-dev"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-trusty-5.0"] } }

    # OS X Yosemite 10.10, Apple Clang 6
    - env: CXX_VERSIONS="11;14" TESTS="mpark"
      compiler: clang
      os: osx
      osx_image: xcode6.4

    # OS X El Capitan 10.11, Apple Clang 7
    - env: CXX_VERSIONS="11;14;1z" TESTS="mpark"
      compiler: clang
      os: osx
      osx_image: xcode7.3

    # OS X Sierra 10.12, Apple Clang 8
    - env: CXX_VERSIONS="11;14;1z" TESTS="mpark"
      compiler: clang
      os: osx
      osx_image: xcode8.3

    - stage: deploy
      before_install:
      install:
      before_script:
        - git config --global user.name "Travis CI"
        - git config --global user.email "<>"
        - travis_retry git clone https://$GITHUB_TOKEN@github.com/mpark/variant --depth 1 --branch=single-header single-header &>/dev/null
      script:
        - SHA=$(git rev-parse --short HEAD)
        - python support/single-header.py > single-header/master/variant.hpp
        - pushd single-header
        - |
          if git diff-index --quiet HEAD --; then
            echo "Nothing to do. No changes were made to 'variant.hpp'."
          else
            git add --all
            git commit -m "Updated 'variant.hpp' @${SHA}."
            travis_retry git pull --rebase && git push origin single-header &>/dev/null
          fi
        - popd

install:
  # Install newer CMake on OS X.
  - |
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update
      brew upgrade cmake
    fi
  # Set the correct `CC` and `CXX` environment variables.
  - |
    if [ -n "${VER}" ]; then
      export CC="${CC}-${VER}"
      export CXX="${CXX}-${VER}"
    fi

script:
  - |
    python - <<EOF
    import os
    import pprint
    import subprocess
    result = {}
    for cxx_version in "${CXX_VERSIONS}".split(';'):
      os.environ['CXXFLAGS'] = '-std=c++{}'.format(cxx_version)
      for build_type in ['Debug', 'Release']:
        for exceptions in ['OFF', 'ON']:
          config = '{}-{}-{}'.format(cxx_version, build_type, exceptions)
          build_dir = 'build-{}'.format(config)
          os.mkdir(build_dir)
          os.chdir(build_dir)
          result[config] = [
            ['configure', None], ['build', None], ['test', None]
          ]
          result[config][0][1] = subprocess.call([
            'cmake', '-DCMAKE_BUILD_TYPE={}'.format(build_type),
                     '-DMPARK_VARIANT_EXCEPTIONS={}'.format(exceptions),
                     '-DMPARK_VARIANT_INCLUDE_TESTS={}'.format("${TESTS}"),
                     '..'])
          if result[config][0][1] == 0:
            result[config][1][1] = subprocess.call([
              'cmake', '--build', '.', '--', '-k', '-j', '2'])
            result[config][2][1] = subprocess.call([
              'ctest', '--output-on-failure'])
          os.chdir('..')
    pprint.pprint(result)
    exit(any(status != 0 for l in result.itervalues() for _, status in l))
    EOF

notifications:
  email: false
