/****************************************************
 * This file is generated by cmake.  Modify the top
 * level CMakeLists.txt to change the VERSION numbers
 ****************************************************/

#define VERSION_MAJOR 4
#define VERSION_MINOR 5
#define VERSION_PATCH 0
#define TLSH_HASH     "compact hash"
#define TLSH_CHECKSUM "1 byte checksum"

#define buckets                      128
#define TLSH_CHECKSUM_LEN            1
#define EFF_BUCKETS                  128
#define CODE_SIZE                    32
#define MIN_DATA_LENGTH              50
#define MIN_CONSERVATIVE_DATA_LENGTH 256
#define TLSH_STRING_LEN_REQ          72
#define INTERNAL_TLSH_STRING_LEN     70
